name: Build Custom Geosite
on:
  workflow_dispatch: # 仅手工触发

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'

      - name: Build mysite.dat
        run: |
          # 运行编译工具
          # --exportlists 只指定你 data 文件夹下存在的文件名（Tag）
          go run ./main.go --datapath=./data --exportlists=cn,cnb
          
          # 生成校验和
          sha256sum mysite.dat > mysite.dat.sha256sum

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: Custom Geosite Build ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            mysite.dat
            mysite.dat.sha256sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
